name: Test

on:
  push:
    branches: [ "main", "action/publish" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Unit Test
        run: dotnet test tests/UnitTest

  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Unit Test
        run: dotnet test tests/UnitTest
